### ISSUE TITLE
ALSA support

### ISSUE THREAD

**Issue by balsoft** [collinss/Cinnamon-Soundbox#21]
I'm _almost_ certain that it's impossible due to the cinnamon itself not supporting ALSA, but maybe there is some hack or workaround to make this beautiful desklet work with ALSA?

**Comment by collinss** [comment]
Hi @balsoft, I don't think it is something that can be done currently (though I can't be sure without doing some research). Cinnamon uses PA because there is a library which allows it to interface with PA from the Cinnamon ui. There may be one for ALSA that works, but I can't be sure it is installed on the user's machine. In addition, I don't use ALSA, so testing might be difficult.

Also, I'm really busy right now with other projects. If someone wanted to do the leg-work and figure out how to make it work, I would certainly accept a pr, but I don't plan to do anything of the sort right now.
